version: '3.8'

services:
  frontend:
    build:
      context: ./vite-site
    ports:
      - "8020:8020"
    environment:
      - VITE_BACKEND_URL=/api
      - VITE_IS_MOCK_API=false
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    ports:
      - "8021:8021"
    depends_on:
      - postgres
    environment:
      - PORT=8021
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    networks:
      - app-network

  postgres:
    image: ankane/pgvector:latest
    ports:
      - "8022:5432"
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge 